#! /bin/sh
### BEGIN INIT INFO
# Provides:          starman
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Run Starman
### END INIT INFO


PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
    start)
        starman --user openbib --port 8008 --workers 30 --backlog 4096 -D --error-log /var/log/openbib/starman.log --pid /var/log/openbib/starman.pid /opt/openbib/conf/portal.psgi
        ;;
    reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    restart)
        $0 stop
        $0 start
        ;;        
    stop)
        kill `cat /var/log/openbib/starman.pid`
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
