SELECT run_on_partitions('searchfields','ALTER TABLE PARTITION ADD CONSTRAINT fk_PARTITION_session FOREIGN KEY (sid) REFERENCES sessioninfo (id)');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_sid ON PARTITION USING btree(sid)');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_id ON PARTITION USING btree(id)');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_tstamp ON PARTITION USING btree(tstamp)');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_tstamp_year ON PARTITION USING btree(tstamp_year)');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_tstamp_month ON PARTITION USING btree(tstamp_month)');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_tstamp_day ON PARTITION USING btree(tstamp_day)');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_viewname ON PARTITION USING btree(viewname)');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_freesearch ON PARTITION USING btree(freesearch) WHERE freesearch IS TRUE');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_title ON PARTITION USING btree(title) WHERE title IS TRUE');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_person ON PARTITION USING btree(person) WHERE person IS TRUE');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_corporatebody ON PARTITION USING btree(corporatebody) WHERE corporatebody IS TRUE');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_subject ON PARTITION USING btree(subject) WHERE subject IS TRUE');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_classification ON PARTITION USING btree(classification) WHERE classification IS TRUE');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_isbn ON PARTITION USING btree(isbn) WHERE isbn IS TRUE');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_issn ON PARTITION USING btree(issn) WHERE issn IS TRUE');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_mark ON PARTITION USING btree(mark) WHERE mark IS TRUE');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_mediatype ON PARTITION USING btree(mediatype) WHERE mediatype IS TRUE');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_titlestring ON PARTITION USING btree(titlestring) WHERE titlestring IS TRUE');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_source ON PARTITION USING btree(source) WHERE source IS TRUE');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_year ON PARTITION USING btree(year) WHERE year IS TRUE');
SELECT run_on_partitions('searchfields','CREATE INDEX PARTITION_content ON PARTITION USING btree(content) WHERE content IS TRUE');
SELECT run_on_partitions('eventlog','ALTER TABLE PARTITION ADD CONSTRAINT fk_PARTITION_session FOREIGN KEY (sid) REFERENCES sessioninfo (id)');
SELECT run_on_partitions('eventlog','CREATE INDEX PARTITION_id ON PARTITION USING btree(id)');
SELECT run_on_partitions('eventlog','CREATE INDEX PARTITION_sid ON PARTITION USING btree(sid)');
SELECT run_on_partitions('eventlog','CREATE INDEX PARTITION_tstamp ON PARTITION USING btree(tstamp)');
SELECT run_on_partitions('eventlog','CREATE INDEX PARTITION_tstamp_year ON PARTITION USING btree(tstamp_year)');
SELECT run_on_partitions('eventlog','CREATE INDEX PARTITION_tstamp_month ON PARTITION USING btree(tstamp_month)');
SELECT run_on_partitions('eventlog','CREATE INDEX PARTITION_tstamp_day ON PARTITION USING btree(tstamp_day)');
SELECT run_on_partitions('eventlog','CREATE INDEX PARTITION_type ON PARTITION USING btree(type)');
SELECT run_on_partitions('eventlog','CREATE INDEX PARTITION_content ON PARTITION USING btree(content text_pattern_ops)');
SELECT run_on_partitions('eventlogjson','ALTER TABLE PARTITION ADD CONSTRAINT fk_PARTITION_session FOREIGN KEY (sid) REFERENCES sessioninfo (id)');
SELECT run_on_partitions('eventlogjson','CREATE INDEX PARTITION_id ON PARTITION USING btree(id)');
SELECT run_on_partitions('eventlogjson','CREATE INDEX PARTITION_sid ON PARTITION USING btree(sid)');
SELECT run_on_partitions('eventlogjson','CREATE INDEX PARTITION_type ON PARTITION USING btree(type)');
SELECT run_on_partitions('eventlogjson','CREATE INDEX PARTITION_tstamp ON PARTITION USING btree(tstamp)');
SELECT run_on_partitions('eventlogjson','CREATE INDEX PARTITION_tstamp_year ON PARTITION USING btree(tstamp_year)');
SELECT run_on_partitions('eventlogjson','CREATE INDEX PARTITION_tstamp_month ON PARTITION USING btree(tstamp_month)');
SELECT run_on_partitions('eventlogjson','CREATE INDEX PARTITION_tstamp_day ON PARTITION USING btree(tstamp_day)');
SELECT run_on_partitions('titleusage','ALTER TABLE PARTITION ADD CONSTRAINT fk_PARTITION_session FOREIGN KEY (sid) REFERENCES sessioninfo (id)');
SELECT run_on_partitions('titleusage','CREATE INDEX PARTITION_sid ON PARTITION USING btree(sid)');
SELECT run_on_partitions('titleusage','CREATE INDEX PARTITION_tstamp ON PARTITION USING btree(tstamp)');
SELECT run_on_partitions('titleusage','CREATE INDEX PARTITION_tstamp_year ON PARTITION USING btree(tstamp_year)');
SELECT run_on_partitions('titleusage','CREATE INDEX PARTITION_tstamp_month ON PARTITION USING btree(tstamp_month)');
SELECT run_on_partitions('titleusage','CREATE INDEX PARTITION_tstamp_day ON PARTITION USING btree(tstamp_day)');
SELECT run_on_partitions('titleusage','CREATE INDEX PARTITION_viewname ON PARTITION USING btree(viewname)');
SELECT run_on_partitions('titleusage','CREATE INDEX PARTITION_isbn ON PARTITION USING btree(isbn)');
SELECT run_on_partitions('titleusage','CREATE INDEX PARTITION_dbname ON PARTITION USING btree(dbname)');
SELECT run_on_partitions('titleusage','CREATE INDEX PARTITION_id ON PARTITION USING btree(id)');
SELECT run_on_partitions('titleusage','CREATE INDEX PARTITION_origin ON PARTITION USING btree(origin)');
SELECT run_on_partitions('searchterms','ALTER TABLE PARTITION ADD CONSTRAINT fk_PARTITION_session FOREIGN KEY (sid) REFERENCES sessioninfo (id)');
SELECT run_on_partitions('searchterms','CREATE INDEX PARTITION_sid ON PARTITION USING btree(sid)');
SELECT run_on_partitions('searchterms','CREATE INDEX PARTITION_tstamp ON PARTITION USING btree(tstamp)');
SELECT run_on_partitions('searchterms','CREATE INDEX PARTITION_viewname ON PARTITION USING btree(viewname)');
SELECT run_on_partitions('searchterms','CREATE INDEX PARTITION_type ON PARTITION USING btree(type)');
SELECT run_on_partitions('searchterms','CREATE INDEX PARTITION_content ON PARTITION USING btree(content)');
